import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const TARGET_COUNT = 1000;
const MAX_CARD_VALUE = 13;

function gcd(left, right) {
  let a = Math.abs(left);
  let b = Math.abs(right);
  while (b !== 0) [a, b] = [b, a % b];
  return a || 1;
}

function fraction(numerator, denominator, expression) {
  if (denominator < 0) {
    numerator *= -1;
    denominator *= -1;
  }
  const divisor = gcd(numerator, denominator);
  return { numerator: numerator / divisor, denominator: denominator / divisor, expression };
}

function solve(numbers) {
  const seen = new Set();

  function search(values) {
    if (values.length === 1) {
      return values[0].numerator === 24 * values[0].denominator ? values[0].expression : null;
    }

    const key = values
      .map((value) => `${value.numerator}/${value.denominator}`)
      .sort()
      .join('|');
    if (seen.has(key)) return null;
    seen.add(key);

    for (let leftIndex = 0; leftIndex < values.length; leftIndex += 1) {
      for (let rightIndex = leftIndex + 1; rightIndex < values.length; rightIndex += 1) {
        const left = values[leftIndex];
        const right = values[rightIndex];
        const remaining = values.filter((_, index) => index !== leftIndex && index !== rightIndex);
        const candidates = [
          fraction(
            left.numerator * right.denominator + right.numerator * left.denominator,
            left.denominator * right.denominator,
            `(${left.expression}+${right.expression})`,
          ),
          fraction(
            left.numerator * right.denominator - right.numerator * left.denominator,
            left.denominator * right.denominator,
            `(${left.expression}-${right.expression})`,
          ),
          fraction(
            right.numerator * left.denominator - left.numerator * right.denominator,
            left.denominator * right.denominator,
            `(${right.expression}-${left.expression})`,
          ),
          fraction(
            left.numerator * right.numerator,
            left.denominator * right.denominator,
            `(${left.expression}*${right.expression})`,
          ),
        ];

        if (right.numerator !== 0) {
          candidates.push(fraction(
            left.numerator * right.denominator,
            left.denominator * right.numerator,
            `(${left.expression}/${right.expression})`,
          ));
        }
        if (left.numerator !== 0) {
          candidates.push(fraction(
            right.numerator * left.denominator,
            right.denominator * left.numerator,
            `(${right.expression}/${left.expression})`,
          ));
        }

        const uniqueCandidates = new Map();
        for (const candidate of candidates) {
          uniqueCandidates.set(`${candidate.numerator}/${candidate.denominator}`, candidate);
        }

        for (const candidate of uniqueCandidates.values()) {
          const result = search([...remaining, candidate]);
          if (result) return result;
        }
      }
    }

    return null;
  }

  return search(numbers.map((number) => fraction(number, 1, String(number))));
}

function formatExpression(expression) {
  return expression
    .replaceAll('*', ' × ')
    .replaceAll('/', ' ÷ ')
    .replaceAll('+', ' + ')
    .replaceAll('-', ' − ');
}

const puzzles = [];

outer:
for (let first = 1; first <= MAX_CARD_VALUE; first += 1) {
  for (let second = first; second <= MAX_CARD_VALUE; second += 1) {
    for (let third = second; third <= MAX_CARD_VALUE; third += 1) {
      for (let fourth = third; fourth <= MAX_CARD_VALUE; fourth += 1) {
        const numbers = [first, second, third, fourth];
        const solution = solve(numbers);
        if (solution) puzzles.push({ numbers, solution: formatExpression(solution) });
        if (puzzles.length === TARGET_COUNT) break outer;
      }
    }
  }
}

if (puzzles.length !== TARGET_COUNT) {
  throw new Error(`Expected ${TARGET_COUNT} solvable puzzles, generated ${puzzles.length}.`);
}

const rows = puzzles.map((puzzle) => (
  `  { numbers: [${puzzle.numbers.join(', ')}], solution: '${puzzle.solution}' },`
));

const output = [
  '// Generated by scripts/generate-puzzles.mjs. Do not edit this file by hand.',
  '',
  'export type Puzzle = { numbers: [number, number, number, number]; solution: string };',
  '',
  'export const puzzles: Puzzle[] = [',
  ...rows,
  '];',
  '',
].join('\n');

writeFileSync(resolve('app/puzzles.ts'), output, 'utf8');
console.log(`Generated ${puzzles.length} validated puzzles.`);
